version: 1
accounts:
- name: "localCamiWallet"
  coins: [ 100ukii ]
genesis:
  chain_id: kiiventador
  app_state:
    staking:
      params:
        bond_denom: ukii
validators:
- name: "localCamiWallet"
  bonded: 100ukii
  app:
    pruning: "nothing"
  config:
    moniker: "kiiventador"
  client:
    output: "json"
